#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<USAGE
Usage:
  $0 <branch-name> <commit-message> [base-branch] [pr-title] [pr-body-file]

Examples:
  $0 feat/auth-session-bootstrap "feat(auth): add authenticated session page"
  $0 chore/ci-governance-gate "chore(ci): add governance gate" main "chore(ci): governance gate" .github/pull_request_template.md
USAGE
}

if [[ $# -lt 2 ]]; then
  usage
  exit 1
fi

BRANCH_NAME="$1"
COMMIT_MESSAGE="$2"
BASE_BRANCH="${3:-main}"
PR_TITLE="${4:-$COMMIT_MESSAGE}"
PR_BODY_FILE="${5:-}"
SKIP_BRANCH_PREP="${SKIP_BRANCH_PREP:-0}"

require_cmd() {
  local cmd="$1"
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "error: required command not found: $cmd" >&2
    exit 1
  fi
}

require_cmd git

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "error: current directory is not a git repository" >&2
  exit 1
fi

if ! git remote get-url origin >/dev/null 2>&1; then
  echo "error: git remote 'origin' not configured" >&2
  exit 1
fi

CURRENT_BRANCH="$(git branch --show-current)"

if [[ "$SKIP_BRANCH_PREP" != "1" ]]; then
  # Ensure base branch is up to date
  git fetch origin "$BASE_BRANCH"
  if git show-ref --verify --quiet "refs/heads/$BASE_BRANCH"; then
    git checkout "$BASE_BRANCH"
    git pull --ff-only origin "$BASE_BRANCH"
  else
    git checkout -b "$BASE_BRANCH" "origin/$BASE_BRANCH"
  fi

  # Create or switch target branch
  if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
    git checkout "$BRANCH_NAME"
  else
    git checkout -b "$BRANCH_NAME"
  fi
else
  # Ensure we are on target branch when branch prep is skipped
  if git show-ref --verify --quiet "refs/heads/$BRANCH_NAME"; then
    git checkout "$BRANCH_NAME"
  else
    git checkout -b "$BRANCH_NAME"
  fi
fi

# Run governance gate if available
if [[ -x "./scripts/ci/governance-gate.sh" ]]; then
  echo "Running governance gate..."
  ./scripts/ci/governance-gate.sh governance-gate-report.md
fi

# Run test discovery (best-effort)
if command -v npx >/dev/null 2>&1; then
  echo "Running Playwright test discovery..."
  npx playwright test --list --project=chromium >/tmp/create-pr-flow-test-list.log 2>&1 || \
    echo "warning: test discovery failed, check /tmp/create-pr-flow-test-list.log"
fi

# Stage and commit
git add -A
if git diff --cached --quiet; then
  echo "error: no staged changes detected; refusing to create empty PR." >&2
  exit 2
else
  git commit -m "$COMMIT_MESSAGE"
fi

# Push branch
git push -u origin "$BRANCH_NAME"

# Create PR when gh is available and authenticated
if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    if [[ -n "$PR_BODY_FILE" && -f "$PR_BODY_FILE" ]]; then
      gh pr create --base "$BASE_BRANCH" --head "$BRANCH_NAME" --title "$PR_TITLE" --body-file "$PR_BODY_FILE"
    else
      BODY_FILE="$(mktemp)"
      cat > "$BODY_FILE" <<BODY
## Summary
- Automated branch, commit and push flow executed.

## Validation
- Governance gate executed (if configured)
- Playwright test discovery attempted

## Notes
- Generated by scripts/git/create-pr-flow.sh
BODY
      gh pr create --base "$BASE_BRANCH" --head "$BRANCH_NAME" --title "$PR_TITLE" --body-file "$BODY_FILE"
      rm -f "$BODY_FILE"
    fi
  else
    echo "warning: gh found but not authenticated."
    echo "manual command: gh pr create --base '$BASE_BRANCH' --head '$BRANCH_NAME' --title '$PR_TITLE'"
  fi
else
  echo "warning: gh CLI not installed."
  echo "manual command: gh pr create --base '$BASE_BRANCH' --head '$BRANCH_NAME' --title '$PR_TITLE'"
fi

# Return to original branch when possible
if [[ -n "$CURRENT_BRANCH" ]] && git show-ref --verify --quiet "refs/heads/$CURRENT_BRANCH"; then
  git checkout "$CURRENT_BRANCH" >/dev/null 2>&1 || true
fi
